### ISSUE TITLE
zeppelin needs lzo classpath

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/layer-apache-zeppelin#8]
Trying to run sparkcontext (sc.) jobs in zeppelin yields this:

```
Caused by: java.lang.IllegalArgumentException: Compression codec com.hadoop.compression.lzo.LzoCodec not found.
```

That's because zepp needs additional classpath entries to tell it where to find lzo jars.  We fixed this for Spark by including the whole `hadoop classpath` in a SPARK_CLASSPATH envar, but that won't work for zepp.

That's because there is some jar in hadoop's classpath that interferes with a jar from zeppelin.  If we try to add `hadoop classpath` to ZEPPELIN_CLASSPATH_OVERRIDES, we get this:

```
$ head -50 /var/log/zeppelin/zeppelin-ubuntu-plugin-2.out
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/lib/hadoop/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/zeppelin/lib/zeppelin-interpreter-0.5.6-incubating.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/zeppelin/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
16/03/17 23:12:30 INFO conf.ZeppelinConfiguration: Load configuration from file:/etc/zeppelin/conf/zeppelin-site.xml
Exception in thread "main" java.lang.SecurityException: class "javax.servlet.ServletRegistration$Dynamic"'s signer information does not match signer information of other classes in the same package
        at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
        at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.apache.zeppelin.server.ZeppelinServer.setupRestApiContextHandler(ZeppelinServer.java:217)
        at org.apache.zeppelin.server.ZeppelinServer.main(ZeppelinServer.java:93)
```

And zepp fails to start.  The workaround for now is to include the very specific path to lzo.jar in ZEPPELIN_CLASSPATH_OVERRIDES:

```
$ grep OVER /etc/zeppelin/conf/zeppelin-env.sh
ZEPPELIN_CLASSPATH_OVERRIDES=/usr/lib/hadoop/share/hadoop/common/lib/hadoop-lzo-0.4.20-SNAPSHOT.jar
```

This issue is open to make this dynamic in case our hadoop vendor or lzo.jar filename change.

**Comment by kwmonroe** [comment]
Fixed by setting ZEPP_CP_OVERRIDES to our new (as of jbd 6.3.0) HADOOP_EXTRA_CLASSPATH, which is set to the path of any extra jars (currently, just lzo):

https://github.com/juju-solutions/layer-apache-zeppelin/commit/a006b7152acffcfcca5c7103c2784e0b4aa69b60
